### ISSUE TITLE
parcel.moist_adiabat_tables error

### ISSUE THREAD

**Issue by maximemarin** [traupach/xarray_parcel#1]
Hi,

I have been trying to use this very nice package for some CAPE calculations, but run into an error when creating my first moist_adiabat_table nc file:

```
import parcel_functions as parcel
parcel.moist_adiabat_tables(regenerate = True)
```

This code runs into the following error:

```
/***/metpy/calc/thermo.py:1044: RuntimeWarning: overflow encountered in exp
  return mpconsts.nounit.sat_pressure_0c * np.exp(
/***/metpy/calc/thermo.py:1169: RuntimeWarning: invalid value encountered in true_divide
  return molecular_weight_ratio * partial_press / (total_press - partial_press)
 lsoda--  at t (=r1), too much accuracy requested  for precision of machine..  see tolsf (=r2) 
in above,  r1 =  0.2167280934254D+03   r2 =                  NaN
/***/scipy/integrate/_ode.py:1350: UserWarning: lsoda: Excess accuracy requested (tolerances too small).
  warnings.warn('{:s}: {:s}'.format(self.__class__.__name__,
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/***/xarray_parcel-main/modules/parcel_functions.py", line 324, in moist_adiabat_tables
    adiabat_lookup, adiabats = moist_adiabat_lookup(**kwargs)
  File "/***/xarray_parcel-main/modules/parcel_functions.py", line 378, in moist_adiabat_lookup
    pres_idx = xarray.DataArray(pressure_levels[idx], dims=['idx'])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2200 but corresponding boolean dimension is 2196
```

As you can see, the error arises as the pressure_levels and idx are not the same size. This is because profile_temps ends up a different size as pressure levels in the following line:

```
profile_temps = metpy.calc.moist_lapse(
                pressure=pressure_levels*units.hPa,
                temperature=(parcel_temperature+offset)*units.K).m
```

I have worked on a few things to fix it, notably limiting the initial pressure_level array to 2 Pa, which seems to work fine.
I suspect the issue is within the solver_arg arguments in metpy.calc.thermo.py:

```
    solver_args = {'fun': dt, 'y0': temperature,
                   'method': 'LSODA', 'atol': 1e-7, 'rtol': 1.5e-8}
```

Let me know if I am missing something here.

Maxime

**Comment by traupach** [comment]
Hi Maxime,

Thanks a lot for finding and letting me know about this issue. I can confirm that I get the same error when I try to run those lines using a recent version of MetPy. I agree with your analysis as to the source of the problem -- for certain combinations of temperature and pressure, `metpy.calc.moist_lapse` is not able to calculate the moist lapse rates but instead of returning `NaN`, it drops the results and gives an array with inconsistent length. I previously generated lookup tables with the same code so I wonder whether the underlying libraries have been updated in the meantime and now result in this error. 

In any case, to fix it I have updated the default pressure levels for which the lookup tables is generated to go down to 2.5 hPa instead of 0.5 hPa, which should still work fine for most applications.

Cheers,
Tim
